title: "René Kooiker"
author: "René J. Kooiker"
description: "Made with Jekyll"
permalink: /:year/:month/:day/:title
lang: "en"
excerpt_separator: <!--more-->

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About me", icon: address-card} # this is the front page
  - {file: "blog.md", title: "Posts", icon: documents} #Here I'll have my posts

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rkooiker18@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/rjkooiker"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/rene-kooiker/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-titles-from-headings

# makes sure titles don't get replicated from headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
